<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27616" started-at="2017-05-16T00:38:46Z" finished-at="2017-05-16T00:39:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27616" started-at="2017-05-16T00:38:46Z" finished-at="2017-05-16T00:39:14Z">
      <class name="generic.AssertionOne">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:generic.AssertionOne@5ca609]" name="beforeTest" is-config="true" duration-ms="25125" started-at="2017-05-16T06:08:47Z" finished-at="2017-05-16T06:09:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="TestCase1()[pri:1, instance:generic.AssertionOne@5ca609]" name="TestCase1" duration-ms="95" started-at="2017-05-16T06:09:12Z" finished-at="2017-05-16T06:09:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Book Flight Tickets, Air Tickets, Airfare - EaseMyTrip.c] but found [Book Flight Tickets, Air Tickets, Airfare - EaseMyTrip.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Book Flight Tickets, Air Tickets, Airfare - EaseMyTrip.c] but found [Book Flight Tickets, Air Tickets, Airfare - EaseMyTrip.com]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at generic.AssertionOne.TestCase1(AssertionOne.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase1 -->
        <test-method status="PASS" signature="TestCase3()[pri:2, instance:generic.AssertionOne@5ca609]" name="TestCase3" duration-ms="162" started-at="2017-05-16T06:09:12Z" finished-at="2017-05-16T06:09:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase3 -->
        <test-method status="PASS" signature="TestCase2()[pri:3, instance:generic.AssertionOne@5ca609]" name="TestCase2" duration-ms="89" started-at="2017-05-16T06:09:12Z" finished-at="2017-05-16T06:09:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase2 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:generic.AssertionOne@5ca609]" name="afterTest" is-config="true" duration-ms="2041" started-at="2017-05-16T06:09:12Z" finished-at="2017-05-16T06:09:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- generic.AssertionOne -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
